
#spring:
#  application:
#    name: ms-product
#  config:
#    import: configserver:http://localhost:8085
#  profiles:
#    active: default



server:
  port: 8081

spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  application:
    name: ms-product
  data:
    mongodb:
      uri: mongodb+srv://josephadmin:7pc2I3a1YT2iFJcC@mongodb101.bldukdv.mongodb.net/dbbank
#  web:
#    resources:
#      add-mappings: false

webclient:
  base-url-customer: http://localhost:8080

springdoc:
  swagger-ui:
    #    enabled: true
    path: index.html


bank:
  accounts:
    savings:
      maintenanceFee: false
      maxMonthlyTransactions: 10
    current:
      maintenanceFee: true
      maxMonthlyTransactions: -1 # -1 indica sin límite
    fixedDeposit:
      maintenanceFee: false
      maxMonthlyTransactions: 1
      specificTransactionDay: 15 # Ejemplo de un día específico del mes para transacciones
  credits:
    personal:
      maxCreditsPerPerson: 1
    business:
      maxCreditsPerCompany: -1 # -1 indica sin límite
    creditCard:
      personal:
        allowed: true
      business:
        allowed: true